1.Write a NumPy program to get the numpy version and show numpy build configuration. 

In [46]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array is zero. .

In [31]:
x = np.array([1, 2, 3, 4])
print("original array:")
print(x)
print("Test if none of  the element of the said array is zero:")
print(np.all(x))
x = np.array([1, 2, 3, 4])
print("original array:")
print(x)
print("Test if none of the element  of the said array is zero")
print(np.all(x))
      
      

original array:
[1 2 3 4]
Test if none of  the element of the said array is zero:
True
original array:
[1 2 3 4]
Test if none of the element  of the said array is zero
True


4. Write a NumPy program to test whether any of the elements of a given array is non-zero. .

In [34]:
x = np.array([1, 0, 0, 0])
print("original array")
print(x)
print("Test whether any of the elements of a given array is zero")
print(np.any(x))
x = np.array([1, 0, 0, 0])
print("original array")
print(x)
print("Test whether any of the elements of a given array is zero")
print(np.any(x))

original array
[1 0 0 0]
Test whether any of the elements of a given array is zero
True
original array
[1 0 0 0]
Test whether any of the elements of a given array is zero
True


In [ ]:
5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number). 



6. Write a NumPy program to test element-wise for positive or negative infinity. 

In [38]:
a = np.array([1, 0, np.nan, np.inf])
print("original array")
print(a)
print("Test  element-wise for positive and negative infinity:")
print(np.isinf(a))

original array
[ 1.  0. nan inf]
Test  element-wise for positive and negative infinity:
[False False False  True]


7. Write a NumPy program to test element-wise for NaN of a given array.


In [50]:
a = np.array([1, 0, np.nan, np.inf])
print("original array")
print(a)
print("Test element-wise for Nan:")
print(np.isnan(a))

original array
[ 1.  0. nan inf]
Test element-wise for Nan:
[False False  True False]


8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not. 

In [57]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real numbers:")
print(np.isreal(a))
print("Checking for scalar vector:")
print(np.isscalar(3.1) )
print(np.isscalar([3.1]))

original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real numbers:
[False  True  True  True  True False]
Checking for scalar vector:
True
False


9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 


In [58]:
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


In [59]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [60]:
np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100]) 
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[3 5]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:


ValueError: operands could not be broadcast together with shapes (2,) (10,) 

12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. .


14. Write a NumPy program to create an array of the integers from 30 to70. .

In [ ]:
import numpy as np

In [2]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

16. Write a NumPy program to create a 3x3 identity matrix. 


In [24]:
np.array ([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

17. Write a NumPy program to generate a random number between 0 and 1. .

In [7]:
np.random.rand(1)

array([0.73000641])

18. Write a NumPy program to generate an array of 15 random numbers from a
standard normal distribution. .

In [13]:
np.random.standard_normal(15)

array([ 0.97379969,  0.26707657,  0.63327751,  0.46963748,  2.12680821,
       -1.04825292,  1.23823399, -0.93339405, -0.98215471, -0.91762185,
       -0.00722977, -1.08790415,  1.00766459, -0.1905929 ,  0.80466332])

19. Write a NumPy program to create a vector with values ranging from 15 to 55
and print all values except the first and last. .

In [32]:
v= np.arange(15,55)
v[1:-1]
v 

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

20. Write a NumPy program to create a 3X4 array using and iterate over it. .

In [33]:
v=np.arange(0,12).reshape(3,4)
for i in np.nditer(v):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

21. Write a NumPy program to create a vector of length 10 with values evenly
distributed between 5 and 50. .

In [34]:
v= np.linspace(5,50,10)
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

22. Write a NumPy program to create a vector with values from 0 to 20 and
change the sign of the numbers in the range from 9 to 15. .

In [37]:
b=np.arange(0,21)
b[9:15] = b[9:15]*1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

23. Write a NumPy program to create a vector of length 5 filled with arbitrary
integers from 0 to 10. .

In [47]:
a =np.random.randint(0,10,5)
a

array([8, 7, 5, 6, 9])

27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal
elements are 1, the rest are 0. .

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

28. Write a NumPy program to create a 10x10 matrix, in which the elements on
the borders will be equal to 1, and inside 0. .

In [54]:
m = np.zeros((10,10))
m[0:,0] = 1
m[0:,9]= 1
m[0] = 1
m[9] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


29. Write a NumPy program to create a 5x5 zero matrix with elements on the
main diagonal equal to 1, 2, 3, 4, 5. .

In [45]:
a = np.zeros((5,5))
num = 0
for i in range (5):
    num = num+1
    a[i,i] = num
a

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are
staggered, with zeros on the main diagonal. .

In [3]:
import numpy as np
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values. .

In [5]:
x = np.random.random((4, 4, 4))
x

array([[[0.98826337, 0.39246569, 0.90226456, 0.03455041],
        [0.89538461, 0.21463981, 0.31985695, 0.25430552],
        [0.10257266, 0.7066464 , 0.23864306, 0.67543837],
        [0.5675846 , 0.4413419 , 0.06134478, 0.10253171]],

       [[0.58830967, 0.87014213, 0.26923622, 0.29413566],
        [0.68439306, 0.07622918, 0.19635875, 0.47334823],
        [0.23567471, 0.54635309, 0.30311268, 0.44161149],
        [0.23366858, 0.16097992, 0.86767931, 0.90678475]],

       [[0.7753382 , 0.37186679, 0.19079566, 0.33082252],
        [0.45866477, 0.62706841, 0.76265744, 0.29121839],
        [0.7592359 , 0.16160926, 0.36654396, 0.84799985],
        [0.87725793, 0.33646782, 0.73985768, 0.21765572]],

       [[0.11559516, 0.80907554, 0.60345993, 0.55098279],
        [0.44607447, 0.28903795, 0.62383011, 0.30572399],
        [0.11797192, 0.00848474, 0.01601459, 0.26296972],
        [0.65988842, 0.19293365, 0.17163377, 0.32527211]]])

32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array. .

In [12]:
x = np.array([[0,1],[2,3]])
print("original array")
print(x)
print("sum of all elements:")
print(np.sum(x))
print("sum of each column:")
print(np.sum(x, axis=0))
print("sum of each row:")
print (np.sum(x, axis=1))



original array
[[0 1]
 [2 3]]
sum of all elements:
6
sum of each column:
[2 4]
sum of each row:
[1 5]


33. Write a NumPy program to compute the inner product of two given vectors. .

In [13]:
x = np.array([5, 6])
y = np.array([7, 8])
print ("original vectors:")
print(x)
print(y)
print("the inner product of said vectors:")
print(np.dot(x, y))

original vectors:
[5 6]
[7 8]
the inner product of said vectors:
83


34. Write a NumPy program to add a vector to each row of a given matrix. .

In [21]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 1, 1])
print("original vector")
print(v)
print("original matrix")
print(m)
result = np.empty_like(m)
for i in range(4):
    result[i, :] = m[i, :] + v
    print("\nafter adding the vector v to each row of the matrix m:")
    print(result)


original vector
[1 1 1]
original matrix
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

after adding the vector v to each row of the matrix m:
[[ 2  3  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

after adding the vector v to each row of the matrix m:
[[ 2  3  4]
 [ 5  6  7]
 [ 7  8  9]
 [10 11 12]]

after adding the vector v to each row of the matrix m:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 12]]

after adding the vector v to each row of the matrix m:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


35. Write a NumPy program to save a given array to a binary file . .

In [27]:
import os
a = np.array(20)
np.save('temp_arra.npy', a)
print("check if 'temp_arra.npy' exist or not?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
        print(np.array_equal(a, x2)) 

IndentationError: unexpected indent (Temp/ipykernel_8456/938505150.py, line 7)